"""firstttt

Revision ID: 717cc5658be9
Revises: 329365193e42
Create Date: 2022-12-16 16:29:31.867403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '717cc5658be9'
down_revision = '329365193e42'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
